depth = -10;
z = 0;
zlerp = 0;

height = 24;

is_player = false;		// does car belong to player?
can_move = true;		// can car be affected by movement or collision?

max_hp = 100;			// car max health
hp = max_hp;			// car health
hp_display = 1;			// smooth hp thingy
hp_regen_delay = 0;		// delay for health regen

engine_rpm_max = 10000;	// max rpm
engine_rpm = 1000;		// engine rpm
test_rpm = 0;
velocity = 0;			// car's speed
max_velocity = 3000;	// car's max speed
speed_limit = 999;		// vehicle's limit based on global.GAMEPLAY_MEASURE_METRICS, should be used for debugging
wheel_radius = 0.32;	// wheel radius in m
mass = 300;				// vehicle mass, in kg
horsepower = 300;		// horsepower
turn_rate = 0;			// car's turning rate
gear = 1;				// car's gear 
engine_power = 0;		// throttle position
transfer_eff = 0.8;		// transfer efficiency
acceleration = 0;		// acceleration value
braking_power = 25;		// braking magnetude
zspeed = 0;				// vertical 
boost_juice = 0;		// boosting meter
boost_usable = false;	// is boost usable
boost_active = false;	// if boost is using
boost_juice_penalty = 0;// penalty for using boost
hit_immune = 0;
name = "";				// racer name

is_completed = false;	// did vehicle completed race

air_drag_coef = 0.3;	// air drag coefficient
drag_area = 1.2;		// cross sectional area

is_respawning = false;	// car is respawning
engine_sound_interval = 0;

car_id = -1;			// car id

inertia = mass * (wheel_radius * wheel_radius) / 2;		// constant value for car's inertia
c_drag = 0.5 * air_drag_coef * drag_area * AIR_DENSITY;	// constant value for car's air drag
c_rr = 20 * c_drag;										// constant value for car's drag

_z_restrict = true;

// max gear based on difficulty
switch(global.difficulty) {
	case 1:		max_gear = 2; break;
	case 1.25:	max_gear = 3; break;
	case 1.5:	max_gear = 4; break;
	case 1.75:	max_gear = 5; break;
	case 2:		max_gear = 6; break;
}

//gear's ratio
gear_ratio = [3, 2.5, 1.9, 6/4, 10/7, 14/10];
//gear_shift_rpm = [
//	[0, 4000],
//	[3000, 4000],
//	[3550, 3850],
//	[3550, 3650],
//	[3150, 3275],
//	[3050, 3100],
//];
gear_shift_rpm = [
	[0, 4500],
	[3000, 4500],
	[3550, 4500],
	[3550, 4500],
	[3150, 4500],
	[3050, 4500],
];

// drive force required for gear shift
force_shift_rpm = [
	[0, 4000],
	[0, 2000],
	[0, 1000],
	[0, 200],
	[0, 100],
	[0, 100000],
];

for (var g = 0; g < array_length(gear_shift_rpm); g++) {
	gear_shift_rpm[g][0] *= global.difficulty;
	gear_shift_rpm[g][1] *= global.difficulty;
}

diff_ratio = 1.2 + global.difficulty;
gear_shift_wait = 0;		//  time wait to change gear again

accelerating = false;		// flag to check if car is accelerating
braking = false;			// flag to check if car is braking
boosting = false;			// flag to check if car is boosting
turning = 0;				// flag to ceck if car is turning, 1 for left and 2 for right, 0 for neither
push_vector = new Vec2()	// vector for collision 
drive_force = 0;			// the force generated by the engine

// surface check
on_road = false				// check if on road horizontally
vertical_on_road = true;	// check if on road vertically
on_road_index = 0;
nearest_road = undefined;
vec_to_road_3d = new Point3D(0, 0, 0);
vec_to_road = new Point(0, 0);

// visual
odometer_rpm = 0;
odometer_speed = 0;

// timer
crash_timer = {
	TIME_TO_STAND: 2,
	TIME_TO_GET_ON: 2,
	to_stand: -1,
	to_get_on: -1,
	is_walking: false,
}

// ai behavior
ai_behavior = {
	desired_lane: 1,				// desired lane to move to
	reversed_direction: false,		// negative direction on road look up
	part_of_race: false,			// part of the ranking race
	change_lane: function(road_index) {
		/// @function	change_lane(road);
		self.desired_lane = (self.reversed_direction ? irandom(road_index.get_lanes_left()-1): irandom(road_index.get_lanes_right()-1));
	},
}
race_rank = 0;
completed_race_rank = 0;
// audio emitter for engine
engine_sound_emitter = audio_emitter_create();
audio_falloff_set_model(audio_falloff_inverse_distance);
audio_emitter_falloff(engine_sound_emitter, 64, 512, 1);

// misc
last_road_index = 0;					// last road index was checked for off road
image_speed = 0;
vehicle_type = 0;
vehicle_detail_index = 0;
vehicle_detail_subimage = 0;
vehicle_color = {
	primary: 0,
	secondary: 0,
	tetriary: 0,
};
racer_color_replace_dst = [];
dist_along_road = 0;					// how far along the road it is

counter = 0;							// counter for various things
current_cp = 0;							// current nearest control point
bike_obj = noone;						// used to identify where bike is when crashed
render_surface = surface_create(128, 64);

// functions
gear_shift_up = function() {
	//shift up
	if (gear+1 < max_gear) {
		engine_power = 0;
		gear_shift_wait = 60;
	}
	gear = min(gear+1, min(max_gear, array_length(gear_shift_rpm)));
	gear_shift_wait = 60;
}

gear_shift_down = function() {
	//shift down
	if (gear-1 > 0) {
		gear_shift_wait = 60;
		engine_power = 0;
	}
	gear = max(gear-1, 1);
	gear_shift_wait = 60;
}

gear_shift = function() {
	var gear_shift_rpm_upper = gear_shift_rpm[gear-1][1]
	var gear_shift_rpm_lower = gear_shift_rpm[gear-1][0];
	
	if (gear_shift_wait <= 0) {
		if (accelerating) {
			if (engine_rpm > 9000 or drive_force < force_shift_rpm[gear-1][1]) {
				gear_shift_up();
			}
		}
		if (!accelerating or braking or !on_road) {
			if ((engine_rpm < gear_shift_rpm_lower)) {
				gear_shift_down();
			}
		}
	}
}

is_on_road = function(_x, _y, road_id) {
	/// @function			is_on_road(x, y, index)
	var proj = point_to_line_3d(
		on_road_index.x, on_road_index.y, on_road_index.z,
		on_road_index.next_road.x, on_road_index.next_road.y, on_road_index.next_road.z,
		x, y, z
	);
	vec_to_road_3d = proj;
	
	proj = point_to_line(
		on_road_index.x, on_road_index.y,
		on_road_index.next_road.x, on_road_index.next_road.y,
		x, y
	);
	vec_to_road = proj;
	var side = sign(dcos(point_direction(x, y, proj.x, proj.y) - on_road_index.direction + 90)); // sign to make sure that value is -1 or 1
	var dist = point_distance(x, y, proj.x, proj.y);

	if (side == -1) {
		// right
		return (dist < (on_road_index.get_lanes_right()+1) * on_road_index.lane_width)
	}
	if (side == 1) {
		// left
		return (dist < (on_road_index.get_lanes_left()+1) * on_road_index.lane_width)
	}
	return false;
}

set_on_road = function() {
	nearest_road = find_nearest_road(x, y, on_road_index._id, 0, ai_behavior.reversed_direction);

	last_road_index = nearest_road._id;
	var polygon_x = obj_road_generator.road_list[last_road_index].get_collision_x();
	var polygon_y = obj_road_generator.road_list[last_road_index].get_collision_y();
	var on_segment = pnpoly(4, polygon_x, polygon_y, x, y);
	var last_on_road = on_road;
	if (!on_segment) {
		if (last_road_index-1 > 0) {
			last_road_index -= 1;
			return obj_road_generator.road_list[last_road_index];
		}
	}
	if (on_road_index.zone == ZONE.RIVER and !last_on_road) {
		on_road = false;
	}
	return obj_road_generator.road_list[last_road_index];
}

on_respawn = function() {
	if (is_respawning) {
		//x = on_road_index.x + lengthdir_x(on_road_index.get_lanes_right() * on_road_index.lane_width, on_road_index.direction - 90);
		//y = on_road_index.y + lengthdir_y(on_road_index.get_lanes_right() * on_road_index.lane_width, on_road_index.direction - 90);
		x = bike_obj.x;
		y = bike_obj.y;
		image_alpha = 1;
		//solid = true;
		mask_index = sprite_index;
		gear = 1;
		
		hp = max_hp;
		can_move = true;
		push_vector.x = 0;
		push_vector.y = 0;
		is_respawning = false;
		z = on_road_index.z;
		on_road = true;
		vertical_on_road = true;
		instance_destroy(bike_obj);
	}
}

on_stand_up = function() {
	// performs when standing up is done
	var road = obj_road_generator.road_list[on_road_index._id + irandom_range(-2,2)];
	hp += 1;
	if (!instance_exists(bike_obj)) {
		bike_obj = instance_create_layer(
			road.x + lengthdir_x((road.get_lanes_right()+0.5) * road.lane_width, road.direction - 90),
			road.y + lengthdir_y((road.get_lanes_right()+0.5) * road.lane_width, road.direction - 90),
			"Instances",
			obj_crashed_bike
		);
		bike_obj.vehicle_color = vehicle_color;
		bike_obj.racer_color_replace_dst = racer_color_replace_dst;
		bike_obj.z = road.z;
		bike_obj.image_angle = road.direction;
		
		if (on_road_index.zone == ZONE.RIVER && !on_road) {
			road = obj_road_generator.road_list[on_road_index._id - 3];
			x = road.x + lengthdir_x(road.get_lanes_right() * road.lane_width, road.direction - 90);
			y = road.y + lengthdir_y(road.get_lanes_right() * road.lane_width, road.direction - 90);
		}
	}
}

on_death = function() {
	if (!is_respawning) {
		instance_create_layer(x, y, "Instances", obj_explosion);
		if (ai_behavior.part_of_race) {
			image_alpha = 0;
			is_respawning = true;
			boosting = false;
			can_move = false;
			//solid = false;
			mask_index = spr_empty;
			direction = on_road_index.direction;
			z += height / 2;
			if (global.DEBUG_PRINT_VEHICLE_CRASH_REASON) {
				print($"object {id} (part_of_race: {ai_behavior.part_of_race}, reverse: {ai_behavior.reversed_direction}) destroyed. Crashed");
			}
		}
		else {
			if (global.DEBUG_PRINT_VEHICLE_CRASH_REASON) {
				print($"object {id} (part_of_race: {ai_behavior.part_of_race}, reverse: {ai_behavior.reversed_direction}) destroyed. HP: {hp}");
			}
			instance_destroy();
		}
		//velocity = 0;
		//gear = 1;
		//rpm = 1000;
		turn_rate = 0;
		boost_active = false;
		engine_power = 0;
	}
}

on_collision_with_entity = function() {
	if (other == self) {return;}
	if (abs(other.z - z) > other.height) {return;}
	
	var dir = point_direction(other.x,other.y,x,y);
	var side = sign(angle_difference(dir, direction));
	var force = ((mass * velocity) + (other.mass + other.velocity)) / global.deltatime;
	var base_collision_hp_lost = (force / 500000);
	if (!is_completed) {
		if (hit_immune <= 0) {
			var collision_sound_max_dist = 256;
			var collision_sound_fall_off = 196;
					
			if (abs(angle_difference(direction, dir)) < 120) {
				base_collision_hp_lost /= 2;
			}
			turn_rate = sign(force) * side * (other.mass / mass) / 10;
			hp -= base_collision_hp_lost;
					
			if (base_collision_hp_lost < 20) {
				audio_play_sound_at(snd_hit_light, x, y, z, collision_sound_fall_off, collision_sound_max_dist, 1, false, 6);
			}
			else if (base_collision_hp_lost < 50) {
				audio_play_sound_at(snd_hit_med, x, y, z, collision_sound_fall_off, collision_sound_max_dist, 1, false, 6);
			}
			else {
				audio_play_sound_at(snd_hit_hard, x, y, z, collision_sound_fall_off, collision_sound_max_dist, 1, false, 6);
			}
			hit_immune = 1;
		}
	}
	push_vector.y += abs(force);
	if (hp <= 0) {
		zspeed += abs(((vehicle_type == VEHICLE_TYPE.BIKE ? height/2 : height) - other.height) / 4) * (velocity / max_velocity);
		turn_rate = 0;
	}
	
	if (is_respawning and other.object_index != obj_prop) {
		if (crash_timer.is_walking) {
			hp = 0;
			on_death();
			crash_timer.is_walking = false;
			crash_timer.to_get_on = -1;
			crash_timer.to_stand = crash_timer.TIME_TO_STAND;
		}
	}
	move_contact_solid(dir,10);
	move_and_collide(dcos(dir), dsin(dir), obj_car_parent);
	hp_regen_delay = -3;
}

//set up vertex buffers
vertex_format_begin();
vertex_format_add_position_3d();	// 12 bytes
vertex_format_add_color();			// 4 bytes
vertex_format_add_texcoord();		// 8 btyes
vertex_format_add_normal();			// 12 bytes
vehicle_vertex_format = vertex_format_end();
vehicle_vertex_buffer = vertex_create_buffer();

// vertex buffer for rendering
vertex_begin(vehicle_vertex_buffer, vehicle_vertex_format);
vertex_position_3d_uv(vehicle_vertex_buffer, 0, 0, 0, 0, 0);
vertex_position_3d_uv(vehicle_vertex_buffer, 0, 0, 0, 0, 0);
vertex_position_3d_uv(vehicle_vertex_buffer, 0, 0, 0, 0, 0);
vertex_position_3d_uv(vehicle_vertex_buffer, 0, 0, 0, 0, 0);
vertex_position_3d_uv(vehicle_vertex_buffer, 0, 0, 0, 0, 0);
vertex_position_3d_uv(vehicle_vertex_buffer, 0, 0, 0, 0, 0);
vertex_end(vehicle_vertex_buffer);

update_vertex_buffer = function() {
	var scaling = {
		w: 0.25,
		h: 0.625
	};
	if (vehicle_type != VEHICLE_TYPE.BIKE) {
		scaling = {
			w: 0.5,
			h: 1
		};
	}
	var w = surface_get_width(render_surface) * scaling.w;
	var h = surface_get_height(render_surface) * scaling.h;
	var tex = surface_get_texture(render_surface);
	var uv = texture_get_uvs(tex);
	var x0 = lengthdir_x(w, image_angle+90);
	var y0 = lengthdir_y(w, image_angle+90);
	var x1 = lengthdir_x(w, image_angle-90);
	var y1 = lengthdir_y(w, image_angle-90);
	var coord_order = [
		[x0, y0, h, uv[0], uv[1]],
		[x0, y0, 0,	uv[0], uv[3]],
		[x1, y1, h, uv[2], uv[1]],
		[x1, y1, h, uv[2], uv[1]],
		[x0, y0, 0, uv[0], uv[3]],
		[x1, y1, 0, uv[2], uv[3]],
	];
	vertex_delete_buffer(vehicle_vertex_buffer);
	vehicle_vertex_buffer = vertex_create_buffer();
	
	vertex_begin(vehicle_vertex_buffer, vehicle_vertex_format);
	for (var i = 0; i < array_length(coord_order); i ++) {
		vertex_position_3d_uv(
			vehicle_vertex_buffer,
			coord_order[i][0],
			coord_order[i][1],
			coord_order[i][2],
			coord_order[i][3],
			coord_order[i][4]
		);
	}
	vertex_end(vehicle_vertex_buffer);

	//for (var i = 0; i < buffer_get_size(buff); i += 36) {
	//	var offset = i div 36;
	//	var coord_x = coord_order[offset][0];
	//	var coord_y = coord_order[offset][1];
	//	var coord_z = coord_order[offset][2];
	//	var u = coord_order[offset][3];
	//	var v = coord_order[offset][4];
	//	// update vertex 3d position
	//	buffer_poke(buff, i + 00, buffer_f32, coord_x);
	//	buffer_poke(buff, i + 04, buffer_f32, coord_y);
	//	buffer_poke(buff, i + 08, buffer_f32, coord_z);
	//	// update texture uv
	//	buffer_poke(buff, i + 16 + 00, buffer_f32, u);
	//	buffer_poke(buff, i + 16 + 04, buffer_f32, v);
	//}
	
	//vehicle_vertex_buffer = vertex_create_buffer_from_buffer(buff, vehicle_vertex_format);
	//buffer_delete(buff);
}

alarm[0] = 1;
alarm[1] = 1200;