/*********** DO NOT EDIT HERE **************/
/*********** SCROLL DOWN **************/
#region Initial data region
depth = -10;
z = 0;
zlerp = 0;

height = 24;

is_player = false;		// does car belong to player?
can_move = true;		// can car be affected by movement or collision?

max_hp = 100;			// car max health
hp = max_hp;			// car health
hp_display = 1;			// smooth hp thingy
hp_regen_delay = 0;		// delay for health regen

engine_rpm_max = 10000;	// max rpm
engine_rpm = 1000;		// engine rpm
test_rpm = 0;
velocity = 0;			// car's speed
max_velocity = 3000;	// car's max speed
wheel_radius = 0.32;	// wheel radius in m
mass = 300;				// vehicle mass, in kg
horsepower = 300;		// horsepower
turn_rate = 0;			// car's turning rate
gear = 1;				// car's gear 
engine_power = 0;		// throttle position
transfer_eff = 0.8;		// transfer efficiency
acceleration = 0;		// acceleration value
braking_power = 25;		// braking magnetude
zspeed = 0;				// vertical 
boost_juice = 0;		// boosting meter
boost_usable = false;	// is boost usable
boost_active = false;	// if boost is using
boost_juice_penalty = 0;// penalty for using boost

is_completed = false;	// did vehicle completed race

air_drag_coef = 0.3;	// air drag coefficient
drag_area = 1.2;		// cross sectional area

is_respawning = false;	// car is respawning
engine_sound_interval = 0;

car_id = -1;			// car id

inertia = mass * (wheel_radius * wheel_radius) / 2;		// constant value for car's inertia
c_drag = 0.5 * air_drag_coef * drag_area * AIR_DENSITY;	// constant value for car's air drag
c_rr = 20 * c_drag;										// constant value for car's drag

_z_restrict = true;

// max gear based on difficulty
switch(global.difficulty) {
	case 1:		max_gear = 3; break;
	case 1.25:	max_gear = 4; break;
	case 1.5:	max_gear = 5; break;
	case 1.75:	max_gear = 5; break;
	case 2:		max_gear = 6; break;
}

//gear's ratio
// gear_ratio = [3, 2.5, 2, 5/3, 10/7, 11/9];
gear_ratio = [3, 2.25, 1.9, 5/3, 10/7, 12/9];
//gear_shift_rpm = [
//	[0, 4500],
//	[2000, 4250],
//	[2750, 4000],
//	[2750, 4000],
//	[2750, 4000],
//	[2750, 2750],
//];
//gear_shift_rpm = [
//	[0, 9000],
//	[4000, 8500],
//	[5500, 8000],
//	[5500, 8000],
//	[5500, 8000],
//	[5500, 5500],
//];
//gear_ratio = [2.66, 1.78, 1.3, 1, 0.74, 0.5];
gear_shift_rpm = [
	[0, 4000],
	[1000, 4000],
	[1550, 3750],
	[1750, 3550],
	[2050, 3275],
	[2500, 3100],
];
for (var g = 0; g < array_length(gear_shift_rpm); g++) {
	gear_shift_rpm[g][0] *= global.difficulty;
	gear_shift_rpm[g][1] *= global.difficulty;
}

diff_ratio = 1.2 + global.difficulty;
gear_shift_wait = 0;		//  time wait to change gear again

accelerating = false;		// flag to check if car is accelerating
braking = false;			// flag to check if car is braking
boosting = false;			// flag to check if car is boosting
turning = 0;				// flag to ceck if car is turning, 1 for left and 2 for right, 0 for neither
push_vector = new Vec2()	// vector for collision 
drive_force = 0;			// the force generated by the engine

// surface check
on_road = false				// check if on road horizontally
vertical_on_road = true;	// check if on road vertically
on_road_index = find_nearest_road(x, y, 0);
nearest_road = undefined;

// visual
odometer_rpm = 0;
odometer_speed = 0;
#endregion

/*********** EDIT HERE **************/
can_move = false;
velocity = 900;
z = 0;

on_road_index = obj_road_generator.road_list[0];
dist_along_road = 0;

vehicle_type = VEHICLE_TYPE.NONE;
vehicle_detail_index = spr_1x1;


last_mouse_x = window_mouse_get_x();