function factorial(n) {
	/// @function		factorial(n)
	/// @description	Calculate n!
	/// @param {int}	n
	/// @return {int}	The result of n!
	assert(n < 0);
	assert(typeof(n) != "number");
	if (n <= 1) {
        return 1;
    }
    else {
        return n * factorial(n - 1);
    }
}

function modulo(a, b) {
    return ((a % b + b) % b);
}

function ncr(n, r) {
	assert((n < 0) or (r < 0) or (r > n), "n and r must be non-negative integers, and r must be less than or equal to n.");
	return factorial(n) div (factorial(r) * factorial(n - r));
}

function lerp_3d(a, b, t) {
	/// @function		lerp_3d(a, b, t)
	/// @description	perform lerp between 2 3d points
	assert(typeof(a) == "array");
	assert(typeof(b) == "array");
	var xl = lerp(a[0], b[0], t);
	var yl = lerp(a[1], b[1], t);
	var zl = lerp(a[2], b[2], t);
	return [xl, yl, zl];
}

function lines_intersect(x1, y1, x2, y2, x3, y3, x4, y4) {
	/// @function		lines_intersect(x1, y1, x2, y2, x3, y3, x4, y4)
	/// @description	Find the point of intersect between the lines that is generated by 1-2 and 3-4
	/// @param {float}	x1
	/// @param {float}	y1
	/// @param {float}	x2
	/// @param {float}	y2
	/// @param {float}	x3
	/// @param {float}	y3
	/// @param {float}	x4
	/// @param {float}	y5
	/// @return {struct}	if there is an intersect, struct's variable intersect will be true and x and y will return the intersection point
    var denom = (y4 - y3) * (x2 - x1) - (x4 - x3) * (y2 - y1);
    
    // Check if lines are parallel (denominator is zero)
    if (denom == 0) {
        return {intersect: false};
    }
    
    var s = ((x4 - x3) * (y1 - y3) - (y4 - y3) * (x1 - x3)) / denom;
    var t = ((x2 - x1) * (y1 - y3) - (y2 - y1) * (x1 - x3)) / denom;
    // Check if the intersection point is within both line segments
    if (s >= 0 && s <= 1 && t >= 0 && t <= 1) {
        // Calculate the intersection point
        var ix = x1 + s * (x2 - x1);
        var iy = y1 + s * (y2 - y1);
        return {intersect: true, x: ix, y: iy};
    } else {
        return {intersect: false}; // No intersection within line segments
    }
}

function calculate_angle_between_lines(x1, y1, x2, y2, x3, y3, x4, y4) {
	/// @function		calculate_angle_between_lines(x1, y1, x2, y2, x3, y3, x4, y4)
	/// @description	find the angle of incident of two lines 
	/// @param {float}	x1
	/// @param {float}	y1
	/// @param {float}	x2
	/// @param {float}	y2
	/// @param {float}	x3
	/// @param {float}	y3
	/// @param {float}	x4
	/// @param {float}	y5
	/// @return {float}	angle of incident
	var m1, m2;
	var is_vertical1 = (x2 - x1 == 0);
	var is_vertical2 = (x4 - x3 == 0);

	// Handle vertical lines
	if (is_vertical1 && is_vertical2) {
		return 0; // Both lines are vertical, so the angle is 0 degrees
	} else if (is_vertical1) {
		// First line is vertical
		m2 = (y4 - y3) / (x4 - x3);
		return radtodeg(arctan(abs(1 / m2))); // Angle between vertical and second line
	} else if (is_vertical2) {
		// Second line is vertical
		m1 = (y2 - y1) / (x2 - x1);
		return radtodeg(arctan(abs(1 / m1))); // Angle between vertical and first line
	} else {
		// Neither line is vertical
		m1 = (y2 - y1) / (x2 - x1);
		m2 = (y4 - y3) / (x4 - x3);
		return radtodeg(arctan(abs((m2 - m1) / (1 + m1 * m2))));
	}
}
