/// @desc Generate an aray of points for triangle
/// @param {Struct.Point3D} p1 Point
/// @param {Struct.Point3D} p2 Point
/// @param {Struct.Point3D} p3 Point
/// @param {Struct.Point} uv1 UV for p1
/// @param {Struct.Point} uv2 UV for p2
/// @param {Struct.Point} uv3 UV for p2
/// @param {Constants.Color} [color] Color for triange (defaults to c_white)
/// @param {real} [alpha] Alpha of triangle (defaults to 1)
/// @returns {array[]} array of points
function polygon_create_triangle_points_3d(p1, p2, p3, uv1, uv2, uv3, color=c_white, alpha=1) {
	return [
		[p1, uv1, color, alpha],
		[p2, uv2, color, alpha],
		[p3, uv3, color, alpha],
	]
}


/// @func			            polygon_create_square_points_3d(p1, p2, p3, p4, uv);
/// @description		        generate a square in the points listed in the order of the argument
/// @param {Struct.Point3D}             p1 Point
/// @param {Struct.Point3D}             p2 Point
/// @param {Struct.Point3D}             p3 Point
/// @param {Struct.Point3D}             p4 Point
/// @param {array}                      uv generated by sprite_get_uvs for texture_get_uvs
/// @param {Constants.Color}            [color]=c_white color of polygon (defaults to c_white)
/// @param {real}                       [alpha]=1 alpha of polygon (defaults to 1)
/// @return array                       array of items [point, value]
function polygon_create_square_points_3d(p1, p2, p3, p4, uv, color=c_white, alpha=1) {
	/* points
	p1 --- p2
	|	  /|
	|   /  |
	| /	   |
	p4 --- p3
	
	uv
	0,1 --- 2,1
	|	   /|
	|    /  |
	|  /    |
	0,3 --- 2,3
	*/
	var t1 = polygon_create_triangle_points_3d(p1, p4, p2, new Point(uv[0], uv[1]), new Point(uv[0], uv[3]), new Point(uv[2], uv[1]), color, alpha);
	var t2 = polygon_create_triangle_points_3d(p2, p4, p3, new Point(uv[2], uv[1]), new Point(uv[0], uv[3]), new Point(uv[2], uv[3]), color, alpha);
	return array_concat(t1, t2);
}
