function polygon_create_triangle_points_3d(p1, p2, p3, uv1, uv2, uv3) {
	return [
		[p1, uv1],
		[p2, uv2],
		[p3, uv3],
	]
}


/// @func			    polygon_create_square_points_3d(p1, p2, p3, p4, uv);
/// @description		generate a square in the points listed in the order of the argument
/// @param p1           Point
/// @param p2           Point
/// @param p3           Point
/// @param p4           Point
/// @param uv			uv generated by sprite_get_uvs for texture_get_uvs
/// @return array       array of items [point, value]
function polygon_create_square_points_3d(p1, p2, p3, p4, uv) {
	/* points
	p1 --- p2
	|	  /|
	|   /  |
	| /	   |
	p4 --- p3
	
	uv
	0,1 --- 2,1
	|	   /|
	|    /  |
	|  /    |
	0,3 --- 2,3
	*/
	var t1 = polygon_create_triangle_points_3d(p1, p4, p2, new Point(uv[0], uv[1]), new Point(uv[0], uv[3]), new Point(uv[2], uv[1]));
	var t2 = polygon_create_triangle_points_3d(p2, p4, p3, new Point(uv[2], uv[1]), new Point(uv[0], uv[3]), new Point(uv[2], uv[3]));
	return array_concat(t1, t2);
}
